AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - vendor/**/*
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Exclude:
    - config/initializers/money.rb
    
Metrics/BlockLength:
  Exclude:
    - config/initializers/simple_form_bootstrap.rb
    - Guardfile
    - spec/models/entry_spec.rb
    - spec/controllers/categories_controller_spec.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/20180125201545_devise_create_users.rb
    - app/controllers/home_controller.rb

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update
    
Metrics/AbcSize:
  Exclude:
    - app/controllers/home_controller.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/controllers/home_controller.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/controllers/home_controller.rb
